# Generated by Django 6.1.1 on 2026-09-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
    ]
